services:
  cache:
    image: 'redis'
    container_name: 'crm_cache'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  crm-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm_server
    image: 'my-crm-image'
    ports:
      - '8000:8000'
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - cache
      - db

  db:
    image: 'postgres:17'
    container_name: crm_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=base-app
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    depends_on:
      - cache

volumes:
  db-data:
  redis-data:
